package com.maliao.crudDemo.entity;

public class Users3 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Tue Nov 29 17:21:44 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.tel
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.pwd
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.head_img
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    private String headImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.remark
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Tue Nov 29 17:21:44 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.tel
     *
     * @return the value of users.tel
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.tel
     *
     * @param tel the value for users.tel
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account
     *
     * @return the value of users.account
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account
     *
     * @param account the value for users.account
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.pwd
     *
     * @return the value of users.pwd
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.pwd
     *
     * @param pwd the value for users.pwd
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.head_img
     *
     * @return the value of users.head_img
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.head_img
     *
     * @param headImg the value for users.head_img
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.remark
     *
     * @return the value of users.remark
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.remark
     *
     * @param remark the value for users.remark
     *
     * @mbggenerated Tue Nov 29 17:21:45 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}